import { relations, sql } from "drizzle-orm";
import { boolean, index, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Team member accounts (ADR 0004, ADR 0006): the tables Better Auth needs, generated by its CLI
 * (`@better-auth/cli generate`, username + admin plugins) and adapted: the account table is `team_member`
 * (CONTEXT.md avoids "user"), IDs are UUIDs (ST-003), times carry the time zone.
 * `email` is required by Better Auth but never shown or used – it holds `<username>@users.invalid` (ADR 0006).
 */
export const teamMember = pgTable("team_member", {
  id: uuid("id")
    .default(sql`gen_random_uuid()`)
    .primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  username: text("username").unique(),
  displayUsername: text("display_username"),
  /** "helper" | "technician" – read again on every request (ST-004). */
  role: text("role"),
  /** Deactivated account (ST-005) – Better Auth's admin plugin calls it "banned". */
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires", { withTimezone: true }),
});

export const session = pgTable(
  "session",
  {
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: uuid("team_member_id")
      .notNull()
      .references(() => teamMember.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"),
  },
  (table) => [index("session_team_member_id_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: uuid("team_member_id")
      .notNull()
      .references(() => teamMember.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_team_member_id_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const teamMemberRelations = relations(teamMember, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  teamMember: one(teamMember, { fields: [session.userId], references: [teamMember.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  teamMember: one(teamMember, { fields: [account.userId], references: [teamMember.id] }),
}));

/**
 * Failed logins per username, for the throttling rule (ST-004): 10 failures within 15 minutes lock the username
 * for 15 minutes. Better Auth's own rate limit counts per IP address, not per username.
 */
export const failedLogin = pgTable(
  "failed_login",
  {
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    username: text("username").notNull(),
    failedAt: timestamp("failed_at", { withTimezone: true }).notNull(),
  },
  (table) => [index("failed_login_username_failed_at_idx").on(table.username, table.failedAt)],
);
